version: '2'

services: 
  prestashop:
    image: lhornok/mission08:1.0
    ports:
      - 8002:80
    links:
      - mysqldb
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: +QAY2wsx3edc
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashopuser
      MYSQL_PASSWORD: +QAY2wsx3edc
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
