<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsw6yz6\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsw6yz6/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIsw6yz6.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIsw6yz6\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerIsw6yz6\appTestDebugProjectContainer([
    'container.build_hash' => 'Isw6yz6',
    'container.build_id' => '1f0d2eae',
    'container.build_time' => 1600020644,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsw6yz6');
